name: Run Checks

on: pull_request

permissions:
  id-token: write
  contents: read

jobs:
  run-checks:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    timeout-minutes: 15
    env:
      NODE_OPTIONS: '--max_old_space_size=8192'
      # force turborepo not to cache, because we are using the same runner for all jobs, across different OSes :
      TURBO_FORCE: 'true'

    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/setup
        with:
          turbo_team: ${{ secrets.TURBO_TEAM }}
          turbo_token: ${{ secrets.TURBO_TOKEN }}
      - run: pnpm run check:dep
      - run: pnpm run check:sherif
      - run: pnpm run check:oxlint
      - run: pnpm run check:format
      - run: pnpm run check:eslint
      - run: pnpm run check:bplint
      - run: pnpm run check:type
      - run: pnpm run test
