name: Run Cognitive Tests

on: pull_request

permissions:
  id-token: write
  contents: read

jobs:
  run-cognitive-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      NODE_OPTIONS: '--max_old_space_size=8192'
      CLOUD_API_ENDPOINT: 'https://api.botpress.dev'
      CLOUD_BOT_ID: a30e30d5-0c00-4831-86ae-4c39155c5b8a # cognitive-tests
      CLOUD_PAT: ${{ secrets.STAGING_TOKEN_CLOUD_OPS_ACCOUNT}}
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/setup
        with:
          turbo_team: ${{ secrets.TURBO_TEAM }}
          turbo_token: ${{ secrets.TURBO_TOKEN }}
          extra_filters: '-F @botpress/cognitive'
      - run: |
          pnpm -F cognitive run test:e2e
